project:
  type: website
  output-dir: docs
  
  
website: 
  title: "The La Selva-Barva MetaNetwork"
  site-url: https://space-lab-msu.github.io/LaSelvaMetaNetwork.github.io/
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - text: "Species"
        menu: 
          - href: plants.qmd
            text: 'Plants'
          - href: mammals.qmd
            text: 'Mammals'
        
format:
  html:
    theme:
      - lux
      